name = "Vanilla Perfected"
author = "Lenny"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d21b94457b1e87632a922f97aa9212a3e65bc6e06b1d1074e5803401c3552ce9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
