name = "Vanilla Perfected"
author = "Lenny"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5300ea0f16ecb0e2b107cfa1fd4410513c902ef5b198d7066c548c6e1dac7531"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
